"""empty message

Revision ID: 14d8a44cf26
Revises: 3e83d6e96d4
Create Date: 2015-03-05 18:38:52.041997

"""

# revision identifiers, used by Alembic.
revision = '14d8a44cf26'
down_revision = '3e83d6e96d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publications', type_='foreignkey')
    op.drop_column('publications', 'added_by')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('added_by', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'publications', 'users', ['added_by'], ['id'])
    ### end Alembic commands ###
