"""empty message

Revision ID: 28a4765393d
Revises: 595b9861296
Create Date: 2015-02-28 10:17:30.876528

"""

# revision identifiers, used by Alembic.
revision = '28a4765393d'
down_revision = '595b9861296'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
