"""initial migration

Revision ID: 2c2435585e4
Revises: None
Create Date: 2015-02-28 00:58:18.273544

"""

# revision identifiers, used by Alembic.
revision = '2c2435585e4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
