"""empty message

Revision ID: 3e83d6e96d4
Revises: 4b56a1fc15c
Create Date: 2015-03-05 18:22:29.228803

"""

# revision identifiers, used by Alembic.
revision = '3e83d6e96d4'
down_revision = '4b56a1fc15c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
