"""empty message

Revision ID: 4b56a1fc15c
Revises: 2ca90ee6635
Create Date: 2015-03-05 17:55:49.190946

"""

# revision identifiers, used by Alembic.
revision = '4b56a1fc15c'
down_revision = '2ca90ee6635'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
