"""empty message

Revision ID: 4db3ec23f2e
Revises: 28a4765393d
Create Date: 2015-02-28 10:23:38.178712

"""

# revision identifiers, used by Alembic.
revision = '4db3ec23f2e'
down_revision = '28a4765393d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
