"""empty message

Revision ID: 595b9861296
Revises: None
Create Date: 2015-02-28 10:06:56.365574

"""

# revision identifiers, used by Alembic.
revision = '595b9861296'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
